[package]
name = "ftop-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psutil = "3.2.2"
indicatif = "0.16.2"
clap = "3.1.18"
owo-colors = "3.4.0"
crossterm = "0.23.2"